module Domain

	NOMBRE    = 50
	EMAIL     = 150
	TELEFONO  = 50
	DIRECCION = 100
	MONEDA 	  = 3
	IVA       = 2
	CODIGO    = 15
	RUC       = 20
	EDAD      = 3
	SEXO      = 9
	CONDICION = 7
	CUOTA     = 3
	CANT_DIAS = 3
	ESTADO    = 15
	DESCRIPCION    = 100
	TIPO_PERSONA   = 9
	NUMERO_DOC_IDE = 10
	NUMERO_DOC_COM = 15
	ABREVIATURA    = 5
	TIPO_MERCADERIA	= 10

end